Added new functions in Numbers

diff --git a/Numbers b/Numbers
--- a/Numbers
+++ b/Numbers
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-function isFloat {
+function isFloat() {
 if [ $# -ne 1 ]; then
 	echo false
 	return 1
@@ -25,7 +25,7 @@ return 0
 # 1 - Not enough parameters
 }
 
-function isInteger {
+function isInteger() {
 if [ $# -ne 1 ]; then
 	echo false
 	return 1
@@ -50,7 +50,7 @@ return 0
 # 1 - Not enough parameters
 }
 
-function isNumber {
+function isNumber() {
 if [ $# -ne 1 ]; then
 	echo false
 	return 1
@@ -77,7 +77,7 @@ return 0
 # 1 - Not enough parameters
 }
 
-function isScientificNotation {
+function isScientificNotation() {
 if [ $# -ne 1 ]; then
 	echo false
 	return 1
@@ -102,4 +102,91 @@ return 0
 # 1 - Not enough parameters
 }
 
-exit 0
+function normalizeFloat() {
+if [ $# -ne 1 ]; then
+	return 1
+fi
+
+param=$1
+if ! $(isFloat $param); then
+	return 2
+fi
+
+if $(isScientificNotation $param); then
+	return 3
+fi
+
+# Chosen method: split the number at the floating point:
+# 1. The integer part is normalized by using "normalizeInteger"
+# 2. The float part is normalized by removing the trailing zeros.
+#    If the float part is omitted, a zero is added after the floating point
+
+# Splitting
+integer=$(echo "$param" | cut -d "." -f 1)
+float=$(echo "$param" | cut -d "." -f 2)
+
+# Normalizing integer part
+inorm=$(normalizeInteger $integer)
+
+# Normalizing float part
+fnorm=$(echo "$float" | sed 's/0*$//')
+# If the number is just a sequency of zeros , the last sed will remove all of them.
+# If the float part is also empty, this check solves that by setting fnorm=0
+if [ -z "$fnorm" ]; then 
+	fnorm=0
+fi
+
+res="$inorm.$fnorm"
+
+echo $res
+return 0
+
+# Return codes
+# 0 - OK
+# 1 - Not enough parameters
+# 2 - Input is not float
+# 3 - Scientific notation numbers is not allowed, although, they are float! 
+}
+
+function normalizeInteger() {
+if [ $# -ne 1 ]; then
+	return 1
+fi
+
+param=$1
+if ! $(isInteger $param); then
+	return 2
+fi
+
+signal=$(echo "$param" | grep "^[+-]" | cut -c 1)
+
+if [ -z "$signal" ]; then
+	number=$param
+else
+	number=$(echo "$param" | sed "s/^$signal//")
+fi
+
+# Remove number's leading zeros
+res=$(echo "$number" | sed 's/^0*//')
+# If the number is just a sequency of zeros, the last sed will remove all of them.
+# If it is also empty, this check solves that by setting res=0 
+if [ -z "$res" ]; then
+	res=0
+fi
+
+# Place again the "-" before negative numbers. The "+" is supressed in positive ones. 
+if [ "$signal" == "-" ]; then
+	if [ $res -ne 0 ]; then # If the number is zero but is preceded by "-", the signal is supressed in this check
+		res=-$res
+	fi
+fi
+
+echo $res
+return 0
+
+# Return codes
+# 0 - OK
+# 1 - Not enough parameters
+# 2 - Input is not integer
+} 
+
